name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build platformio image
      run: make -C docker platformio-image
    - name: build platformio project
      run: make -C docker pio DOCKEROPTS=--tty=false EXEC="pio run"
