name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build image
      run: make -C docker docker-platformio
    - name: build
      run: make -C docker pio DOCKEROPTS=--tty=false EXEC="pio run"
