name: Check code format

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build uncrustify image
      run: make -C docker uncrustify-image
    - name: check code format
      run: make -C lifesensor DOCKEROPTS=--tty=false check-format
