name: Build project lifesensor

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build idf image
      run: make -C docker idf-image
    - name: build idf project
      run: make -C lifesensor DOCKEROPTS=--tty=false build
